name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Check formatting
        run: terraform fmt -check -recursive
        working-directory: .

      - name: Init (no backend)
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate